baseURL = "https://blog.f10.org"
languageCode = "en-us"
title = "ChinoBing's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "ChinoBing"
  homepage = "https://github.com/chinobing/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
headTitle = "Chino Bing"
Description = "The best is yet to come."
disqus = "" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About Me"
link = "https://blog.f10.org/posts/1_%E5%85%B3%E4%BA%8E/"
[[params.socials]]
name = "Github"
link = "https://github.com/chinobing"
