baseURL = "https://blog.f10.org"
languageCode = "en-us"
title = "ChinoBing's Blog"
theme = ["hugo-admonitions", "yinyang"
DefaultContentLanguage = "cn"

#[author]
#  name = "ChinoBing"
#  homepage = "https://github.com/chinobing/"

[languages]
  # [languages.en]
  #   contentDir = "content/en"
  #   languageName = "English"
  #   weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
headTitle = "Chino Bing"
Description = "The best is yet to come."
disqus = "" # disqus account name
extraHead = ''
mainSections = ["posts"]

# due to .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release.
[params.author]
  name = "ChinoBing"
  homepage = "https://github.com/chinobing/"

[params.giscus]
repo = "chinobing/chinobing.github.io"
repoID = "R_kgDONWX1gw"
category = "Announcements"
categoryID = "DIC_kwDONWX1g84Ckyj5"
mapping = "og:title"
data-strict="0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "light"
lang = "zh-CN"
loading = "lazy"


[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About Me"
link = "https://blog.f10.org/posts/1_%E5%85%B3%E4%BA%8E/"
[[params.socials]]
name = "Github"
link = "https://github.com/chinobing"
